; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Vitesse du moniteur série
monitor_speed = 115200

; Force l'utilisation de votre port détecté
;upload_port = /dev/cu.usbserial-210

; Vitesse de téléversement
;upload_speed = 115200
; Vitesse ultra-rapide standard
upload_speed = 921600

; Gestion des bibliothèques (ajoute les noms ou ID ici)
lib_deps = 
    https://github.com/Nkawu/TFT_22_ILI9225.git
    jled
    https://github.com/InfectedBytes/ArduinoShiftIn.git

